/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Booking,
  City,
  District,
  Hotel,
  PaymentsEcpayPostRequest,
  Room,
} from '../models/index';
import {
    BookingFromJSON,
    BookingToJSON,
    CityFromJSON,
    CityToJSON,
    DistrictFromJSON,
    DistrictToJSON,
    HotelFromJSON,
    HotelToJSON,
    PaymentsEcpayPostRequestFromJSON,
    PaymentsEcpayPostRequestToJSON,
    RoomFromJSON,
    RoomToJSON,
} from '../models/index';

export interface BookingsPostRequest {
    booking?: Booking;
}

export interface DistrictsGetRequest {
    cityId?: string;
}

export interface HotelsGetRequest {
    cityId?: string;
    starRating?: number;
}

export interface HotelsHotelIdRoomsGetRequest {
    hotelId: string;
}

export interface PaymentsEcpayPostOperationRequest {
    paymentsEcpayPostRequest?: PaymentsEcpayPostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * 建立訂房
     */
    async bookingsPostRaw(requestParameters: BookingsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bookings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookingToJSON(requestParameters['booking']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 建立訂房
     */
    async bookingsPost(requestParameters: BookingsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bookingsPostRaw(requestParameters, initOverrides);
    }

    /**
     * 取得城市列表
     */
    async citiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<City>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/cities`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CityFromJSON));
    }

    /**
     * 取得城市列表
     */
    async citiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<City>> {
        const response = await this.citiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 依城市取得行政區
     */
    async districtsGetRaw(requestParameters: DistrictsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<District>>> {
        const queryParameters: any = {};

        if (requestParameters['cityId'] != null) {
            queryParameters['city_id'] = requestParameters['cityId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/districts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DistrictFromJSON));
    }

    /**
     * 依城市取得行政區
     */
    async districtsGet(requestParameters: DistrictsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<District>> {
        const response = await this.districtsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 搜尋飯店（含圖片）
     */
    async hotelsGetRaw(requestParameters: HotelsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Hotel>>> {
        const queryParameters: any = {};

        if (requestParameters['cityId'] != null) {
            queryParameters['city_id'] = requestParameters['cityId'];
        }

        if (requestParameters['starRating'] != null) {
            queryParameters['star_rating'] = requestParameters['starRating'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hotels`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(HotelFromJSON));
    }

    /**
     * 搜尋飯店（含圖片）
     */
    async hotelsGet(requestParameters: HotelsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Hotel>> {
        const response = await this.hotelsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 取得飯店房型與庫存
     */
    async hotelsHotelIdRoomsGetRaw(requestParameters: HotelsHotelIdRoomsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Room>>> {
        if (requestParameters['hotelId'] == null) {
            throw new runtime.RequiredError(
                'hotelId',
                'Required parameter "hotelId" was null or undefined when calling hotelsHotelIdRoomsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/hotels/{hotel_id}/rooms`;
        urlPath = urlPath.replace(`{${"hotel_id"}}`, encodeURIComponent(String(requestParameters['hotelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoomFromJSON));
    }

    /**
     * 取得飯店房型與庫存
     */
    async hotelsHotelIdRoomsGet(requestParameters: HotelsHotelIdRoomsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Room>> {
        const response = await this.hotelsHotelIdRoomsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 由 booking 建立付款單
     */
    async paymentsEcpayPostRaw(requestParameters: PaymentsEcpayPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/payments/ecpay`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentsEcpayPostRequestToJSON(requestParameters['paymentsEcpayPostRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * 由 booking 建立付款單
     */
    async paymentsEcpayPost(requestParameters: PaymentsEcpayPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.paymentsEcpayPostRaw(requestParameters, initOverrides);
    }

}
