/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Review } from './Review';
import {
    ReviewFromJSON,
    ReviewFromJSONTyped,
    ReviewToJSON,
    ReviewToJSONTyped,
} from './Review';
import type { Room } from './Room';
import {
    RoomFromJSON,
    RoomFromJSONTyped,
    RoomToJSON,
    RoomToJSONTyped,
} from './Room';
import type { Hotel } from './Hotel';
import {
    HotelFromJSON,
    HotelFromJSONTyped,
    HotelToJSON,
    HotelToJSONTyped,
} from './Hotel';

/**
 * 
 * @export
 * @interface Booking
 */
export interface Booking {
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    profileId: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    hotelId: string;
    /**
     * 
     * @type {string}
     * @memberof Booking
     */
    roomId: string;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    checkInDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    checkOutDate: Date;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    nights: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    guestCount: number;
    /**
     * 
     * @type {number}
     * @memberof Booking
     */
    totalPrice: number;
    /**
     * 與 DB enum 一致
     * @type {string}
     * @memberof Booking
     */
    status: BookingStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof Booking
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Hotel}
     * @memberof Booking
     */
    hotel?: Hotel;
    /**
     * 
     * @type {Room}
     * @memberof Booking
     */
    room?: Room;
    /**
     * 
     * @type {Array<Review>}
     * @memberof Booking
     */
    reviews?: Array<Review>;
}


/**
 * @export
 */
export const BookingStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Cancelled: 'cancelled'
} as const;
export type BookingStatusEnum = typeof BookingStatusEnum[keyof typeof BookingStatusEnum];


/**
 * Check if a given object implements the Booking interface.
 */
export function instanceOfBooking(value: object): value is Booking {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('profileId' in value) || value['profileId'] === undefined) return false;
    if (!('hotelId' in value) || value['hotelId'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('checkInDate' in value) || value['checkInDate'] === undefined) return false;
    if (!('checkOutDate' in value) || value['checkOutDate'] === undefined) return false;
    if (!('nights' in value) || value['nights'] === undefined) return false;
    if (!('guestCount' in value) || value['guestCount'] === undefined) return false;
    if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function BookingFromJSON(json: any): Booking {
    return BookingFromJSONTyped(json, false);
}

export function BookingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Booking {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'profileId': json['profile_id'],
        'hotelId': json['hotel_id'],
        'roomId': json['room_id'],
        'checkInDate': (new Date(json['check_in_date'])),
        'checkOutDate': (new Date(json['check_out_date'])),
        'nights': json['nights'],
        'guestCount': json['guest_count'],
        'totalPrice': json['total_price'],
        'status': json['status'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'hotel': json['hotel'] == null ? undefined : HotelFromJSON(json['hotel']),
        'room': json['room'] == null ? undefined : RoomFromJSON(json['room']),
        'reviews': json['reviews'] == null ? undefined : ((json['reviews'] as Array<any>).map(ReviewFromJSON)),
    };
}

export function BookingToJSON(json: any): Booking {
    return BookingToJSONTyped(json, false);
}

export function BookingToJSONTyped(value?: Booking | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'profile_id': value['profileId'],
        'hotel_id': value['hotelId'],
        'room_id': value['roomId'],
        'check_in_date': value['checkInDate'].toISOString().substring(0,10),
        'check_out_date': value['checkOutDate'].toISOString().substring(0,10),
        'nights': value['nights'],
        'guest_count': value['guestCount'],
        'total_price': value['totalPrice'],
        'status': value['status'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'hotel': HotelToJSON(value['hotel']),
        'room': RoomToJSON(value['room']),
        'reviews': value['reviews'] == null ? undefined : ((value['reviews'] as Array<any>).map(ReviewToJSON)),
    };
}

