/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HotelImage } from './HotelImage';
import {
    HotelImageFromJSON,
    HotelImageFromJSONTyped,
    HotelImageToJSON,
    HotelImageToJSONTyped,
} from './HotelImage';

/**
 * 
 * @export
 * @interface Hotel
 */
export interface Hotel {
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    name: string;
    /**
     * 僅為顯示用
     * @type {string}
     * @memberof Hotel
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    district?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    address?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Hotel
     */
    starRating?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Hotel
     */
    minPrice?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Hotel
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Hotel
     */
    isFeatured?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof Hotel
     */
    featuredOrder?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Hotel
     */
    latitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Hotel
     */
    longitude?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof Hotel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Hotel
     */
    updatedAt?: Date | null;
    /**
     * API層關聯帶入
     * @type {Array<HotelImage>}
     * @memberof Hotel
     */
    images?: Array<HotelImage>;
    /**
     * 由 hotels_facilities 轉入
     * @type {Array<string>}
     * @memberof Hotel
     */
    facilities?: Array<string>;
}

/**
 * Check if a given object implements the Hotel interface.
 */
export function instanceOfHotel(value: object): value is Hotel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function HotelFromJSON(json: any): Hotel {
    return HotelFromJSONTyped(json, false);
}

export function HotelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Hotel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'city': json['city'] == null ? undefined : json['city'],
        'district': json['district'] == null ? undefined : json['district'],
        'address': json['address'] == null ? undefined : json['address'],
        'starRating': json['star_rating'] == null ? undefined : json['star_rating'],
        'minPrice': json['min_price'] == null ? undefined : json['min_price'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'description': json['description'] == null ? undefined : json['description'],
        'isFeatured': json['is_featured'] == null ? undefined : json['is_featured'],
        'featuredOrder': json['featured_order'] == null ? undefined : json['featured_order'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(HotelImageFromJSON)),
        'facilities': json['facilities'] == null ? undefined : json['facilities'],
    };
}

export function HotelToJSON(json: any): Hotel {
    return HotelToJSONTyped(json, false);
}

export function HotelToJSONTyped(value?: Hotel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'city': value['city'],
        'district': value['district'],
        'address': value['address'],
        'star_rating': value['starRating'],
        'min_price': value['minPrice'],
        'phone': value['phone'],
        'description': value['description'],
        'is_featured': value['isFeatured'],
        'featured_order': value['featuredOrder'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(HotelImageToJSON)),
        'facilities': value['facilities'],
    };
}

