/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HotelImage
 */
export interface HotelImage {
    /**
     * 
     * @type {string}
     * @memberof HotelImage
     */
    id: string;
    /**
     * 對應 hotels.id
     * @type {string}
     * @memberof HotelImage
     */
    hotelId: string;
    /**
     * 
     * @type {string}
     * @memberof HotelImage
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof HotelImage
     */
    sortOrder?: number | null;
}

/**
 * Check if a given object implements the HotelImage interface.
 */
export function instanceOfHotelImage(value: object): value is HotelImage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hotelId' in value) || value['hotelId'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function HotelImageFromJSON(json: any): HotelImage {
    return HotelImageFromJSONTyped(json, false);
}

export function HotelImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HotelImage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hotelId': json['hotel_id'],
        'imageUrl': json['image_url'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function HotelImageToJSON(json: any): HotelImage {
    return HotelImageToJSONTyped(json, false);
}

export function HotelImageToJSONTyped(value?: HotelImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hotel_id': value['hotelId'],
        'image_url': value['imageUrl'],
        'sort_order': value['sortOrder'],
    };
}

