/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentsEcpayPostRequest
 */
export interface PaymentsEcpayPostRequest {
    /**
     * 
     * @type {string}
     * @memberof PaymentsEcpayPostRequest
     */
    bookingId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentsEcpayPostRequest
     */
    returnUrl?: string;
}

/**
 * Check if a given object implements the PaymentsEcpayPostRequest interface.
 */
export function instanceOfPaymentsEcpayPostRequest(value: object): value is PaymentsEcpayPostRequest {
    if (!('bookingId' in value) || value['bookingId'] === undefined) return false;
    return true;
}

export function PaymentsEcpayPostRequestFromJSON(json: any): PaymentsEcpayPostRequest {
    return PaymentsEcpayPostRequestFromJSONTyped(json, false);
}

export function PaymentsEcpayPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsEcpayPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookingId': json['booking_id'],
        'returnUrl': json['return_url'] == null ? undefined : json['return_url'],
    };
}

export function PaymentsEcpayPostRequestToJSON(json: any): PaymentsEcpayPostRequest {
    return PaymentsEcpayPostRequestToJSONTyped(json, false);
}

export function PaymentsEcpayPostRequestToJSONTyped(value?: PaymentsEcpayPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'booking_id': value['bookingId'],
        'return_url': value['returnUrl'],
    };
}

