/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    hotelId: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    roomType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    memberName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    memberType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    comment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    stayDate?: Date | null;
}

/**
 * Check if a given object implements the Review interface.
 */
export function instanceOfReview(value: object): value is Review {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hotelId' in value) || value['hotelId'] === undefined) return false;
    return true;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hotelId': json['hotel_id'],
        'roomType': json['room_type'] == null ? undefined : json['room_type'],
        'memberName': json['member_name'] == null ? undefined : json['member_name'],
        'memberType': json['member_type'] == null ? undefined : json['member_type'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'title': json['title'] == null ? undefined : json['title'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'stayDate': json['stay_date'] == null ? undefined : (new Date(json['stay_date'])),
    };
}

export function ReviewToJSON(json: any): Review {
    return ReviewToJSONTyped(json, false);
}

export function ReviewToJSONTyped(value?: Review | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hotel_id': value['hotelId'],
        'room_type': value['roomType'],
        'member_name': value['memberName'],
        'member_type': value['memberType'],
        'rating': value['rating'],
        'title': value['title'],
        'comment': value['comment'],
        'stay_date': value['stayDate'] == null ? value['stayDate'] : value['stayDate'].toISOString().substring(0,10),
    };
}

