/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomInventory
 */
export interface RoomInventory {
    /**
     * 
     * @type {string}
     * @memberof RoomInventory
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoomInventory
     */
    roomId: string;
    /**
     * 
     * @type {Date}
     * @memberof RoomInventory
     */
    date: Date;
    /**
     * 
     * @type {number}
     * @memberof RoomInventory
     */
    totalQuantity: number;
    /**
     * 
     * @type {number}
     * @memberof RoomInventory
     */
    availableQuantity: number;
    /**
     * 
     * @type {Date}
     * @memberof RoomInventory
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof RoomInventory
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the RoomInventory interface.
 */
export function instanceOfRoomInventory(value: object): value is RoomInventory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('totalQuantity' in value) || value['totalQuantity'] === undefined) return false;
    if (!('availableQuantity' in value) || value['availableQuantity'] === undefined) return false;
    return true;
}

export function RoomInventoryFromJSON(json: any): RoomInventory {
    return RoomInventoryFromJSONTyped(json, false);
}

export function RoomInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomInventory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'roomId': json['room_id'],
        'date': (new Date(json['date'])),
        'totalQuantity': json['total_quantity'],
        'availableQuantity': json['available_quantity'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function RoomInventoryToJSON(json: any): RoomInventory {
    return RoomInventoryToJSONTyped(json, false);
}

export function RoomInventoryToJSONTyped(value?: RoomInventory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'room_id': value['roomId'],
        'date': value['date'].toISOString().substring(0,10),
        'total_quantity': value['totalQuantity'],
        'available_quantity': value['availableQuantity'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

