/* tslint:disable */
/* eslint-disable */
/**
 * WanTrip Supabase OpenAPI
 * 飯店訂房與付款會員 資料架構
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomInventory } from './RoomInventory';
import {
    RoomInventoryFromJSON,
    RoomInventoryFromJSONTyped,
    RoomInventoryToJSON,
    RoomInventoryToJSONTyped,
} from './RoomInventory';

/**
 * 
 * @export
 * @interface Room
 */
export interface Room {
    /**
     * 
     * @type {string}
     * @memberof Room
     */
    id: string;
    /**
     * 對應 hotels.id
     * @type {string}
     * @memberof Room
     */
    hotelId: string;
    /**
     * 對應 room_types.id
     * @type {string}
     * @memberof Room
     */
    roomTypeId: string;
    /**
     * 
     * @type {string}
     * @memberof Room
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Room
     */
    capacity?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Room
     */
    imageUrl?: string | null;
    /**
     * 庫存來自 room_inventory
     * @type {Array<RoomInventory>}
     * @memberof Room
     */
    inventory?: Array<RoomInventory>;
}

/**
 * Check if a given object implements the Room interface.
 */
export function instanceOfRoom(value: object): value is Room {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('hotelId' in value) || value['hotelId'] === undefined) return false;
    if (!('roomTypeId' in value) || value['roomTypeId'] === undefined) return false;
    return true;
}

export function RoomFromJSON(json: any): Room {
    return RoomFromJSONTyped(json, false);
}

export function RoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): Room {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'hotelId': json['hotel_id'],
        'roomTypeId': json['room_type_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'price': json['price'] == null ? undefined : json['price'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
        'inventory': json['inventory'] == null ? undefined : ((json['inventory'] as Array<any>).map(RoomInventoryFromJSON)),
    };
}

export function RoomToJSON(json: any): Room {
    return RoomToJSONTyped(json, false);
}

export function RoomToJSONTyped(value?: Room | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'hotel_id': value['hotelId'],
        'room_type_id': value['roomTypeId'],
        'name': value['name'],
        'price': value['price'],
        'capacity': value['capacity'],
        'image_url': value['imageUrl'],
        'inventory': value['inventory'] == null ? undefined : ((value['inventory'] as Array<any>).map(RoomInventoryToJSON)),
    };
}

